version: '3.8'

services:
  frontend:
    image: flashcards-frontend-prod
    container_name: flashcards-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
        - frontend_build:/var/www

  backend:
    image: flashcards-backend-prod
    container_name: flashcards-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/backend
    environment:
      - MDB_URI=${MDB_URI}

  mongo:
    image: mongo
    container_name: mongodb-prod
    ports:
      - 3456:27017
    volumes:
      - ./mongo_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend

volumes:
  frontend_build:
  mongo_data: