version: '3.8'

services:
  backend: 
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: server
    depends_on:
      - nginx

  mongo:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: mongo

  redis:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: redis

  frontend:
    extends:
      file: ./todo-frontend/docker-compose.dev.yml
      service: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    depends_on:
      - nginx

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
